#!/usr/bin/env bash

# Creating the VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specifications '[ResourceType=vpc,Tags=[{Key=Name,Value=my-cli-vpc}]]' \
--region us-east-1 \
--query Vpc.VpcId \
--output text)