#!/usr/bin/env bash

set -e

# Creating the VPC
VPC_ID=$(aws ec2 create-vpc \
    --cidr-block "172.1.0.0/16" \
    --tag-specifications '[ResourceType=vpc,Tags=[{Key=Name,Value=my-cli-vpc}]]' \
    --region us-east-1 \
    --query Vpc.VpcId \
    --output text)

echo "VPC_ID: $VPC_ID"

# turn on hostnames

aws ec2 modify-vpc-attribute \
  --vpc-id $VPC_ID \
  --enable-dns-support

aws ec2 modify-vpc-attribute \
  --vpc-id $VPC_ID \
  --enable-dns-hostnames

# Creating Internet Gateway(IGW)
IGW_ID=$(aws ec2 create-internet-gateway \
    --query InternetGateway.InternetGatewayId \
    --output text)

echo "IGW_ID: $IGW_ID"

# Attach VPC to IGW
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Creating Subnet
SUBNET_ID=$(aws ec2 create-subnet \
    --vpc-id $VPC_ID \
    --cidr-block 172.1.0.0/20 \
    --query Subnet.SubnetId \
    --output text )

echo "SUBNET_ID: $SUBNET_ID"

## Auto Assigne IPv4 Address
aws ec2 modify-subnet-attribute \
    --subnet-id $SUBNET_ID \
    --map-public-ip-on-launch

# associate 
## get the route table
RTB_ID=$(aws ec2 describe-route-tables \
  --filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
  --query "RouteTables[0].RouteTableId[]" \
  --output text)

  #--query "RouteTables[0].RouteTableId" \

echo "RTB_ID: $RTB_ID"

aws ec2 associate-route-table \
    --route-table-id $RTB_ID \
    --subnet-id $SUBNET_ID

# add route to route table
aws ec2 create-route \
  --route-table-id $RTB_ID \
  --destination-cidr-block 0.0.0.0/0 \
  --gateway-id $IGW_ID